# Generated by Django 3.2.8 on 2022-03-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(db_column='emp_name', max_length=50, verbose_name='Emp_Name')),
                ('id_card', models.CharField(db_column='id_card', max_length=50, verbose_name='Id_Card')),
                ('emp_phone', models.BigIntegerField(db_column='emp_phone', verbose_name='Emp_Phone')),
                ('emp_email', models.EmailField(blank=True, db_column='emp_email', max_length=100, null=True, verbose_name='Emp_Email')),
                ('emp_pwd', models.CharField(db_column='emp_pwd', max_length=100, verbose_name='Emp_Password')),
                ('emp_gender', models.CharField(db_column='emp_gender', max_length=50, verbose_name='Emp_Gender')),
                ('emp_date_birth', models.DateField(db_column='emp_date_birth', max_length=50, verbose_name='Emp_Date_Birth')),
                ('emp_education', models.CharField(db_column='emp_education', max_length=50, verbose_name='Emp_Education')),
                ('emp_designation', models.CharField(db_column='emp_designation', max_length=50, verbose_name='Emp_Designation')),
                ('emp_photo', models.ImageField(db_column='emp_photo', upload_to='employees/images/', verbose_name='Emp_Photo')),
                ('emp_addres', models.CharField(db_column='emp_Addres', max_length=50, verbose_name='Emp_Addres')),
            ],
            options={
                'db_table': 'emp_details',
            },
        ),
    ]
