# Generated by Django 3.2.8 on 2022-03-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='id_card',
        ),
    ]
