# Generated by Django 3.2.8 on 2022-03-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_employees_id_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(db_column='pro_name', max_length=50, verbose_name='Pro_Name')),
                ('pro_assigner', models.CharField(db_column='pro_assigner', max_length=50, verbose_name='Pro_Assigner')),
                ('pro_file', models.FileField(db_column='pro_file', upload_to='Project/Project-details/', verbose_name='Pro_File')),
            ],
            options={
                'db_table': 'project_details',
            },
        ),
    ]
