# Generated by Django 3.2.8 on 2022-03-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_date_birth',
            field=models.DateTimeField(db_column='emp_date_birth', max_length=50, verbose_name='Emp_Date_Birth'),
        ),
    ]
