# Generated by Django 3.2.8 on 2022-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_employees_emp_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_addres',
            field=models.CharField(db_column='emp_addres', max_length=50, verbose_name='Emp_Addres'),
        ),
    ]
