# Generated by Django 3.2.8 on 2022-03-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_employees_emp_addres'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ending_date',
            field=models.DateTimeField(db_column='ending_date', max_length=50, null=True, verbose_name='Ending_Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(db_column='start_date', max_length=50, null=True, verbose_name='Start_Date'),
        ),
    ]
