# Generated by Django 3.2.8 on 2022-03-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_employees_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(db_column='status', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
