# Generated by Django 3.2.8 on 2022-03-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(db_column='status', default='Pending', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
