# Generated by Django 3.2.8 on 2022-04-01 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='datetime_created',
            field=models.DateTimeField(db_column='datetime_created ', default=datetime.datetime.now, max_length=50, null=True, verbose_name='Datetime_Created '),
        ),
        migrations.AddField(
            model_name='project',
            name='datetime_created',
            field=models.DateTimeField(db_column='datetime_created ', default=datetime.datetime.now, max_length=50, null=True, verbose_name='Datetime_Created '),
        ),
    ]
