# Generated by Django 3.2.8 on 2022-04-01 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_auto_20220401_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='datetime_created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='datetime_created',
        ),
        migrations.AddField(
            model_name='employees',
            name='datetime',
            field=models.DateTimeField(db_column='datetime ', default=datetime.datetime.now, max_length=50, null=True, verbose_name='Datetime '),
        ),
        migrations.AddField(
            model_name='project',
            name='datetime',
            field=models.DateTimeField(db_column='datetime', default=datetime.datetime.now, max_length=50, null=True, verbose_name='Datetime'),
        ),
    ]
