# Generated by Django 3.2.8 on 2022-04-01 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_auto_20220401_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='datetime',
            field=models.DateTimeField(db_column='datetime ', default=datetime.datetime.now, null=True, verbose_name='Datetime '),
        ),
        migrations.AlterField(
            model_name='project',
            name='datetime',
            field=models.DateTimeField(db_column='datetime', default=datetime.datetime.now, null=True, verbose_name='Datetime'),
        ),
    ]
