# Generated by Django 3.2.8 on 2022-04-01 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_auto_20220401_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
