# Generated by Django 3.2.8 on 2022-04-01 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_employees_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
