# Generated by Django 3.2.8 on 2022-03-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0002_alter_assign_project_emp_assigner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(db_column='pro_name', max_length=50, verbose_name='Pro_Name')),
                ('emp_assigner', models.CharField(db_column='emp_assigner', max_length=50, verbose_name='Emp_Assigner')),
                ('due_date', models.DateTimeField(db_column='due_date', max_length=50, null=True, verbose_name='Due_Date')),
                ('priorty', models.CharField(db_column='priorty', max_length=50, verbose_name='Priorty')),
                ('text', models.TextField(db_column='text', max_length=100, verbose_name='Text')),
            ],
            options={
                'db_table': 'task_details',
            },
        ),
    ]
