# Generated by Django 3.2.8 on 2022-03-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manager_id',
            field=models.CharField(db_column='manager_id', max_length=50, null=True, verbose_name='Manager_Id'),
        ),
    ]
